joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

  # Position Controllers ---------------------------------------
joint1_position:
  type: position_controllers/JointPositionController
  joint: joint1
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position:
  type: position_controllers/JointPositionController
  joint: joint2
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position:
  type: position_controllers/JointPositionController
  joint: joint3
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint4_position:
  type: position_controllers/JointPositionController
  joint: joint4
  pid: {p: 100.0, i: 0.01, d: 10.0}
gripper_position:
  type: position_controllers/JointPositionController
  joint: gripper
  pid: {p: 100.0, i: 0.01, d: 10.0}
gripper_sub_position:
  type: position_controllers/JointPositionController
  joint: gripper_sub
  pid: {p: 100.0, i: 0.01, d: 10.0}
